import { tokenizeMarkdownLine } from "@openp41ge/renderer/controllers/syntax-highlight";

// Quick fuzz: run the tokenizer on many edge-case inputs with a timeout
describe("tokenizeMarkdownLine fuzz", () => {
  const inputs = [
    "",
    " ",
    "  ",
    "\t",
    "a",
    "*",
    "**",
    "***",
    "****",
    "* ",
    " *",
    "** ",
    " ***",
    "a*",
    "a *",
    "a* ",
    "a * ",
    "* a",
    "**a",
    "*a ",
    "* a ",
    "`*`",
    "`* `",
    "```",
    "![",
    "![]",
    "![](",
    "!",
    "! ",
    "a!b",
    "Hello!World",
    "test!",
    "!hello",
    "[]",
    "[](",
    "[*]",
    "[*](",
    "***a***",
    "**a**",
    "*a*",
    "*a*b*",
    "foo * bar * baz",
    "***",
    "*** ",
    " *** ",
    "a *** b",
    "~~~",
    "|",
    ":",
    "~",
    "**foo * bar**",
    "***foo**",
    "***foo***",
    "**foo*",
    "**foo*bar**",
    "* foo",
    "*  foo",
    "- * foo",
    "- **foo**",
    "1. *foo*",
    "> * foo",
    "# *foo*",
    "`code` and *italic* and **bold**",
    "\x00",
    "\t*",
    "*\t",
    "**\t**",
    "a".repeat(1000), // long line
    "*".repeat(1000),
    "a * b * c * d * e * f * g * h * i * j",
    "**bold** *italic* `code` [link](url) ![img](img.png)",
  ];

  for (const input of inputs) {
    it(`handles input ${JSON.stringify(input.slice(0, 40))}`, () => {
      expect(() => tokenizeMarkdownLine(input)).not.toThrow();
    });
  }
});
