/**
 * inline-css.mjs — reads compiled Tailwind CSS and generates a .ts module
 * so components can import it as a string for Lit's static styles.
 *
 * Usage: node scripts/inline-css.mjs
 * Reads:  dist/styles.css
 * Writes: src/generated/tailwind.ts
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(__dirname, "..");

const cssPath = path.join(root, "dist", "styles.css");
const outPath = path.join(root, "src", "generated", "tailwind.ts");

if (!fs.existsSync(cssPath)) {
  console.error("dist/styles.css not found — run build:css first");
  process.exit(1);
}

const css = fs.readFileSync(cssPath, "utf-8");

// Ensure the output directory exists
fs.mkdirSync(path.dirname(outPath), { recursive: true });

// Escape backticks, template literals, and backslashes in the CSS
// Backslashes must be escaped first so CSS escapes like \\2c don't become
// legacy octal escapes in the JS template literal.
const escaped = css
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${");

fs.writeFileSync(
  outPath,
  `// Auto-generated by scripts/inline-css.mjs — do not edit\n// Generated from dist/styles.css\n\nexport const tailwindCSS: string = \`${escaped}\`;\n`,
);

console.log("✓ Generated src/generated/tailwind.ts");
